/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountTable: typeof import('./src/components/AccountTable.vue')['default']
    ActivityCalendar: typeof import('./src/components/ActivityCalendar.vue')['default']
    ActivityTable: typeof import('./src/components/ActivityTable.vue')['default']
    AlbumTable: typeof import('./src/components/AlbumTable.vue')['default']
    CollectionBoxDrop: typeof import('./src/components/CollectionBoxDrop.vue')['default']
    CollectionsTable: typeof import('./src/components/CollectionsTable.vue')['default']
    DropTable: typeof import('./src/components/DropTable.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmploymentDatabase: typeof import('./src/components/EmploymentDatabase.vue')['default']
    EmploymentDatabaseTable: typeof import('./src/components/EmploymentDatabaseTable.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IssueDateTable: typeof import('./src/components/IssueDateTable.vue')['default']
    JobSearchTable: typeof import('./src/components/JobSearchTable.vue')['default']
    MaskLayer: typeof import('./src/components/MaskLayer.vue')['default']
    OrderTable: typeof import('./src/components/OrderTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TypeTable: typeof import('./src/components/TypeTable.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
